---
title: "Accessibility guidance checklist"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{accessibility}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#"
)
```

## Purpose

The purpose of this vignette is to provide a light-tough way of showing how the {a11ytables} package adheres to best practice to create publication-quality workbooks that meet accessibility guidance.

## Checklists

The tables below show how the features of the {a11ytables} package meet [the GSS Best Practice and Impacts Division's 'Making spreadsheets accessible: checklist of the basics'](https://gss.civilservice.gov.uk/policy-store/making-spreadsheets-accessible-a-brief-checklist-of-the-basics/).

This assessment is based on the unedited output from a typical {a11ytables} workflow: a `new_a11ytable()` passed to `create_a11y_wb()` and then `openxlsx::saveWorkbook()`.

The 'status' column in these tables takes the following values for each feature, depending on their implementation:

* Y = yes (completed)
* P = partly (not fully implemented)
* N = no (not yet handled)
* U = user (the user's responsibility)
* NA = not applicable (not relevant to how the package functions)

### 1. Tables

| Number | Description | Essential? | Status |
| :--- | :--- | :--- | :--- | 
| 1 | Mark up tables | Y | Y | 
| 2 | Give tables meaningful names | | U |
| 3 | Remove merged cells, split cells and nested tables | Y | Y |
| 4 | Remove blank rows and columns within tables | Y | Y |
| 5 | All tables should have one tagged header row | Y | Y |
| 6 | Wrap text within cells | Y | Y |
| 7 | Avoid adding filters and freeze panes | | Y |
| 8 | Only leave cells with no data empty in certain circumstances | Y | NA |
| 9 | Avoid hiding rows or columns | | Y |

### 2. Footnotes

| Number | Description | Essential? | Status |
| :--- | :--- | :--- | :--- | 
| 1 | Do not use symbols or superscript to signpost to notes | Y | Y |
| 2 | Use the word ‘note’ when referring to footnotes | | Y |
| 3 | Avoid putting note markers in specific cells | | U |
| 4 | Put note text in a notes table on a notes worksheet | | Y |

### 3. Formatting

| Number | Description | Essential? | Status |
| :--- | :--- | :--- | :--- | 
| 1 | All written content needs to meet the accessibility guidelines | | U |
| 2 | Links must be accessible | Y | U |
| 3 | Format text to make it accessible | | Y |
| 4 | All worksheets should have descriptive titles which are properly tagged and formatted | Y | P |
| 5 | Avoid using symbols in general | | U |
| 6 | Do not use headers and footers, floating text boxes or floating toolbars | Y | Y |
| 7 | Do not use visual devices to divide data regions | | Y |
| 8 | Do not use a background fill | | Y |
| 9 | Do not use colour as the only way to convey a message | Y | Y |
| 10 | When using colour for emphasis check the contrast | Y | NA |
| 11 | Avoid images in spreadsheets | | Y |
| 12 | Remove macros | | Y |

### 4. Structure

| Number | Description | Essential? | Status |
| :--- | :--- | :--- | :--- | 
| 1 | Give worksheets unique names or numbers | Y | Y |
| 2 | Remove blank worksheets | Y | Y |
| 3 | Use cells in column A wisely | Y | U |
| 4 | Position tables against the left-hand edges of each sheet | Y | Y |
| 5 | Avoid putting content below a table | | Y |
| 6 | Avoid worksheets with multiple tables | | Y |

### 5. Before publishing

| Number | Description | Essential? | Status |
| :--- | :--- | :--- | :--- | 
| 1 | Run a spelling and grammar check | Y | U |
| 2 | Use the accessibility checker | | U |
| 3 | Add document information | Y | U |
| 4 | Ensure the cursor is in cell A1 of the first worksheet when doing your final save | Y | Y |
