---
title: "Accessibility guidance checklist"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{accessibility}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#"
)
```

## Purpose

This vignette shows you how {a11ytables} meets accessibility best practice.

## Checklists

The tables below show how the features of the {a11ytables} package meet the GSS Best Practice and Impacts Division's ['Making spreadsheets accessible: checklist of the basics'](https://gss.civilservice.gov.uk/policy-store/making-spreadsheets-accessible-a-brief-checklist-of-the-basics/).

This assessment is based on generating an unedited output from a typical {a11ytables} workflow: a `new_a11ytable()` passed to `create_a11y_wb()` and then written with `openxlsx::saveWorkbook()`.

### Tables

| Description | Essential? | Status | Explanation |
| :-- | :- | :- | :---- |
| Mark up tables | Yes | Included | Automatic table mark-up is provided by `create_a11y_wb()` |
| Give tables meaningful names | No | Included | Unique table names are generated from the `tab_titles` argument in `new_a11ytable()` |
| Remove merged cells, split cells and nested tables | Yes | Included | Not supported by {a11ytables} |
| Remove blank rows and columns within tables | Yes | Partly/user responsibility | A warning is supplied to a user if cells are blank; it's assumed there is a reason for the cells to be blank, which the user should explain in the workbook |
| All tables should have one tagged header row | Yes | Included | R's data.frame class only allows for one header row, which must have unique names; the header row is tagged as such when marked-up as a table |
| Wrap text within cells | Yes | Included | `create_a11y_wb()` wraps content by default; there's a simple check in {a11ytables} to widen a column if it contains long strings |
| Avoid adding filters and freeze panes | No | Included | Filters and freezing aren't supported by {a11ytables} |
| Only leave cells with no data empty in certain circumstances | Yes | User's responsibility | The user should describe why there are blank cells |
| Avoid hiding rows or columns | No | Included | Hiding isn't supported by {a11ytables} |

### Footnotes

| Description | Essential? | Status | Explanation |
| :-- | :- | :- | :---- |
| Do not use symbols or superscript to signpost to notes | Yes | Included/user-responsibility | Notes are detected automatically as digits in square brackets; superscript is not supported by {a11ytables} |
| Use the word 'note' when referring to footnotes | No | User-responsibility | Notes are detected in the form '[note 1]'; the user should be consistent about this wording |
| Avoid putting note markers in specific cells | No | User-responsibility | Columns named 'Notes' and note markers in column headers are detected, the user should not put these elswhere  |
| Put note text in a notes table on a notes worksheet | No | Included | `new_a11ytable()` expects the `sheet_type` 'notes' |

### Formatting

| Description | Essential? | Status | Explanation |
| :-- | :- | :- | :---- |
| All written content needs to meet the accessibility guidelines | | User's responsibility | {a11ytables} does not check the validity of user-supplied text |
| Links must be accessible | Yes | User's responsibility | {a11ytables} does not check the validity of user-supplied text |
| Format text to make it accessible | No | Included | `create_a11y_wb()` auto-formats the text |
| All worksheets should have descriptive titles which are properly tagged and formatted | Yes | User-responsibility/partly | {a11ytables} does not check user-supplied text nor data; the package handles formatting but not yet mark-up for headings |
| Avoid using symbols in general | No | User's responsibility | {a11ytables} does not check the validity of user-supplied text |
| Do not use headers and footers, floating text boxes or floating toolbars | Yes | Included  | These features aren't supported by {a11ytables} |
| Do not use visual devices to divide data regions | No | Included | Colours and patterns aren't supported by {a11ytables} |
| Do not use a background fill | No | Included | Fills aren't supported by {a11ytables} |
| Do not use colour as the only way to convey a message | Yes | Included | Colour is not supported by {a11ytables} |
| When using colour for emphasis check the contrast | Yes | Not applicable | Colour is not supported by {a11ytables}, so a check is not required |
| Avoid images in spreadsheets | No | Included | Images aren't supported by {a11ytables} |
| Remove macros | No | Included | Macros aren't supported by {a11ytables} |

### Structure

| Description | Essential? | Status | Explanation |
| :-- | :- | :- | :---- |
| Give worksheets unique names or numbers | Yes | User's responsibility | Supply `tab_titles` to `new_a11ytable()`, which gives a warning if any names match |
| Remove blank worksheets | Yes | Included | `new_a11ytable()` will error if expected argument content is missing |
| Use cells in column A wisely | Yes | Included | `create_a11y_wb()` inserts the sheet title, table count, notes statement, source statement and tables into column A by default  |
| Position tables against the left-hand edges of each sheet | Yes | Included | `create_a11y_wb()` inserts automatically the tables into column A |
| Avoid putting content below a table | No | Included | `create_a11y_wb()` adds information to rows above tables only |
| Avoid worksheets with multiple tables | No | Included | The package supports only one table per sheet (for now) |

### Before publishing

| Description | Essential? | Status | Explanation |
| :-- | :- | :- | :---- |
| Run a spelling and grammar check | Yes | User's responsibility | These checks aren't supported by {a11ytables}; the user should check using their own software |
| Use the accessibility checker | No | User's responsibility | These checks aren't supported by {a11ytables}; the user should check using their own software |
| Add document information | Yes | User's responsibility | Not yet possible with {a11ytables}; users must do this manually |
| Ensure the cursor is in cell A1 of the first worksheet when doing your final save | Yes | Included | Occurs automatically |
